### PR TITLE
Add parameter 'pageview' (used on ep_page_view plugin)

### PR DESCRIPTION
**Pull request by lpagliari**

### CODE REVIEW

**Comment by storytouch** [comment]
:+1:

**Comment by leandromoreira** [comment]
:+1:

**Comment by storytouch** [comment]
:+1:

**Comment by JohnMcLear** [comment]
There a thousands of possible url parameters exposed by plugins, I think at this point we should extend functionality to allow for a KV object that allows embedded params..

**Comment by JohnMcLear** [comment]
Something like..
```
plugins:{
  pageview: false,
  realtimechat: false
}
```

Thoughts?

**Comment by leandromoreira** [comment]
@JohnMcLear I totally agree

**Comment by lpagliari** [comment]
@JohnMcLear Something like this?

```
$('#examplePadPlugins').pad({'padId':'test',plugins:{'pageview':'true'}});
```

**Comment by JohnMcLear** [comment]
Yeah is that clean enough?
----- Reply message -----

**Comment by lpagliari** [comment]
Yep!

**Comment by lpagliari** [comment]
Was that what you had in mind?

**Comment by JohnMcLear** [comment]
Yep!  Thanks!

**Pull request merged**
