### PR TITLE
Add optional parameter lang

### PR DESCRIPTION
**Pull request by e-nemo**
allow client to force user language instead of using browser prefered language.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Should follow coding conventions, doesn't.  Please review :)

**Comment by e-nemo** [comment]
Sorry, but where are the coding convention for etherpad-lite-jquery-plugin?

**Comment by e-nemo** [comment]
Is it ok now?

**Comment by JohnMcLear** [comment]
Yes thanks :)

**Pull request merged**
